CREATE TABLE docs (
	id VARCHAR(15) PRIMARY KEY,
	uv VARCHAR(5) NOT NULL,
	type VARCHAR(10) NOT NULL,
	nom VARCHAR(255) NOT NULL,
	extension VARCHAR(4),
	note TINYINT,
	semestre CHAR(3)
);


CREATE TABLE uvbranche (
	branche VARCHAR(3) NOT NULL,
	uv VARCHAR(5) NOT NULL,
	titreuv VARCHAR(255) NOT NULL
);