INSERT INTO `uvbranche` (`branche`, `uv`, `titreuv`) VALUES
('TC', 'BL10', 'Structures Et Physicochimie Des Mol&#xE9;cules Biologiques'),
('TC', 'BL22', 'Microbiologie Et Biologie Mol&#xE9;culaire'),
('TC', 'CM01', 'Physique De La Mati&#xE8;re'),
('TC', 'CM11', 'Chimie G&#xE9;n&#xE9;rale'),
('TC', 'CM12', 'Chimie Physique Min&#xE9;rale'),
('TC', 'CM13', 'Chimie Des Substances Organiques Et Biologiques'),
('TC', 'MT23', 'Alg&#xE8;bre Lin&#xE9;aire Et Applications'),
('TC', 'MT91', 'Fonctions D\'Une Variable Reelle 2'),
('TC', 'PS04', 'Thermodynamique'),
('TC', 'PS92', 'Dynamique Des Systemes Et Des Solides'),
('TC', 'SY01', '&#xE9;l&#xE9;ments De Probabilit&#xE9;s'),
('TC', 'TN06', 'Transmission Des Efforts En M&#xE9;canique'),
('TC', 'BL09', 'Biophysique Des Syst&#xE8;mes Biologiques'),
('TC', 'BM01', 'Introduction &#xE0; L\'Instrumentation Biom&#xE9;dicale'),
('TC', 'MT94', 'Introduction Aux Mathematiques Appliqu&#xE9;es'),
('TC', 'NP90', 'Nano-Projets'),
('TC', 'TN03', 'Fabrication M&#xE9;canique'),
('TC', 'TR91', 'Techniques De Recherche D\'Information Pour L\'Ingenieur'),
('TSH', 'AR03','Art Et Technologies Contemporaines'),
('TSH', 'DI01','Initiation Au Design Industriel'),
('TSH', 'DI02','Initiation Au Design Graphique'),
('TSH', 'EI03','Communication Interculturelle En Entreprises, Organisations Transnationales'),
('TSH', 'EI04','Intelligence &#xE9;conomique : Strat&#xE9;gie D\'Entreprise, D&#xE9;marche Et Outils'),
('TSH', 'EI05','Science, Technologie Et Soci&#xE9;t&#xE9; Dans L\'Union Europ&#xE9;enne'),
('TSH', 'GE10','&#xE9;conomie Politique'),
('TSH', 'GE12','G&#xE9;ographie Et &#xE9;conomie Des Territoires'),
('TSH', 'GE13','Les Risques Entre Technique Et Societe'),
('TSH', 'GE15','Initiation A La Cr&#xE9;ation Et Gestion D\'Entreprises Innovantes'),
('TSH', 'GE20','&#xE9;conomie Industrielle'),
('TSH', 'GE21','&#xE9;conomie Et Gestion De L\'Innovation Et Du Num&#xE9;rique'),
('TSH', 'GE22','&#xE9;conomie Internationale'),
('TSH', 'GE23','Transferts De Technologies Et D&#xE9;veloppements'),
('TSH', 'GE24','Recherche Developpement : Ingenieur Et Investisseurs'),
('TSH', 'GE25','Gestion Et Organisation De La Production'),
('TSH', 'GE26','Management Strat&#xE9;gique Des Ressources Humaines'),
('TSH', 'GE28','&#xE9;conomie Et Droit De La Propri&#xE9;t&#xE9; Intellectuelle (Industrielle Et Artistique) Dans Une &#xE9;conomie Reposant Sur La Connaissance'),
('TSH', 'GE29','Gestion Et Management International De L\'Entreprise'),
('TSH', 'GE36','Marketing'),
('TSH', 'GE90','Organisation, Innovation Et International'),
('TSH', 'HE01','&#xE9;pist&#xE9;mologie Et Histoire Des Sciences'),
('TSH', 'HE03','Logique : Histoire Et Formalisme'),
('TSH', 'HE05','Culture Et Histoire Des Techniques'),
('TSH', 'IC01','Histoire Et Prospective Des Industries Culturelles'),
('TSH', 'IC03','Le Num&#xE9;rique : Des Formats Aux Chaines De Production'),
('TSH', 'IC05','Technologies Pour La Documentation Et L\'Indexation Dans L\'Hyperm&#xE9;dia'),
('TSH', 'IC07','Techniques Et Technologies Du Musical Et Du Sonore'),
('TSH', 'LA00','Allemand Initiation'),
('TSH', 'LA01','Allemand Niveau I'),
('TSH', 'LA02','Allemand Niveau II'),
('TSH', 'LA03','Allemand Niveau III'),
('TSH', 'LA04','Pratique De La Communication En Allemand'),
('TSH', 'LA11','Anglais Niveau I'),
('TSH', 'LA12','Anglais Niveau II'),
('TSH', 'LA13','Anglais Niveau III'),
('TSH', 'LA14','Civilisation Du Monde Anglophone'),
('TSH', 'LA15','Anglais Professionnel - Niveau V'),
('TSH', 'LA20','Espagnol Initiation'),
('TSH', 'LA21','Espagnol Niveau I'),
('TSH', 'LA22','Espagnol Niveau II'),
('TSH', 'LA23','Espagnol Niveau III'),
('TSH', 'LA24','Le Monde Hispanique Contemporain : L\'Am&#xE9;rique Latine (Niveau IV)'),
('TSH', 'LA91','Francais Langue &#xE9;trang&#xE8;re Niveau I'),
('TSH', 'LA92','Francais Langue &#xE9;trang&#xE8;re Niveau II'),
('TSH', 'LA93','Francais Langue &#xE9;trang&#xE8;re Niveau III'),
('TSH', 'LA94','Francais Langue &#xE9;trang&#xE8;re Niveau IV'),
('TSH', 'LB04','Interculturalit&#xE9; Franco-Allemande'),
('TSH', 'LB14','Interculturalit&#xE9; Appliqu&#xE9;e Aux Pays Anglophones'),
('TSH', 'LB24','Le Monde Hispanique (Niveau IV): L\'Espagne'),
('TSH', 'LC14','Communication Scientifique Et Technique En Anglais'),
('TSH', 'LG30','Japonais Initiation'),
('TSH', 'LG31','Japonais Niveau I'),
('TSH', 'LG40','Portugais Initiation'),
('TSH', 'LG41','Portugais Niveau I'),
('TSH', 'LG42','Portugais Niveau II'),
('TSH', 'LG50','Italien Initiation'),
('TSH', 'LG51','Italien Niveau I'),
('TSH', 'LG52','Italien Niveau II'),
('TSH', 'LG60','Chinois Initiation'),
('TSH', 'LG61','Chinois Niveau I'),
('TSH', 'MU01','Pratique Instrumentale D\'Ensemble'),
('TSH', 'MU02','Pratique Instrumentale De Haut Niveau'),
('TSH', 'MU03','Pratique Collective Des Musiques Contemporaines'),
('TSH', 'PH01','Introduction &#xE0; La Philosophie'),
('TSH', 'PH09','&#xE9;thiques : Approche Pluridisciplinaire'),
('TSH', 'SA11','Pratiques Th&#xE9;atrales'),
('TSH', 'SC01','S&#xE9;minaire Interdisciplinaire De Sciences Et Technologies Cognitives'),
('TSH', 'SC11','Th&#xE9;orie Des Sciences Cognitives : Computation Et &#xE9;naction'),
('TSH', 'SC12','Technologie, Cognition, Perception'),
('TSH', 'SC21','Linguistique Et Philosophie Du Langage'),
('TSH', 'SC22','Sociologie Cognitive, Lien Social Et Techniques'),
('TSH', 'SI01','Science Et Debat Public'),
('TSH', 'SI02','Communication Professionnelle De L\'Ing&#xE9;nieur'),
('TSH', 'SI05','Theories De La Communication'),
('TSH', 'SI06','La Documentattion Cross-Media Pour Les Entreprises Et Les Collectivites Locales'),
('TSH', 'SI07','Medias Classiques Et Medias Numeriques'),
('TSH', 'SI11','Expression Orale- Parole Publique'),
('TSH', 'SI14','Parole Publique En Anglais'),
('TSH', 'SI20','Rhetorique Et Arts Du Discours'),
('TSH', 'SI22','Signes Et Contenus Numeriques'),
('TSH', 'SI24','&#xE9;tudes Des &#xE9;critures Num&#xE9;riques Ordinaires'),
('TSH', 'SI28','&#xE9;criture Interactive Et Multim&#xE9;dia'),
('TSH', 'SI90','S&#xE9;minaire De Communication Des Connaissances Technologiques'),
('TSH', 'SL','Suivi Linguistique'),
('TSH', 'SO04','Initiation Au Droit'),
('TSH', 'SO05','Sociologie, Organisations Et Dynamiques Des Collectifs'),
('TSH', 'SP01','Un Corps Pour Comprendre Et Apprendre'),
('TSH', 'SP02','Conduire Un Projet Sportif'),
('TSH', 'TN16','&#xE9;tude Interculturelle'),
('TSH', 'TO01','Module De Preparation Au Toeic'),
('HU', 'MT34', 'Analyse 2 : Mesures, Int&#xE9;grations, Probabilit&#xE9;s'),
('HU', 'MT37', 'Logiques, Quelques Approfondissements Math&#xE9;matiques Et Philosophiques'),
('HU', 'MT38', 'Probabilit&#xE9;s'),
('GM', 'CT04', 'Controles Non Destructifs'),
('GM', 'DI03', 'Conception Formelle Des Produits'),
('GM', 'DI06', 'Analyse Des Produits De Consommation'),
('GM', 'EG01', 'Ergonomie'),
('GM', 'EN14', 'Fonctions &#xC9;lectroniques Pour L\'Ing&#xE9;nieur'),
('GM', 'FQ07', 'La Qualit&#xE9; Des Services A L\'Industrie'),
('GM', 'MC01', 'Machines &#xC9;lectriques'),
('GM', 'MC07', '&#xC9;lectronique De Puissance'),
('GM', 'MQ04', 'Polym&#xE8;res'),
('GM', 'MQ08', 'Elaboration Et Proprietes D\'Usage Des Metaux'),
('GM', 'MQ09', 'M&#xE9;canique Des Vibrations II'),
('GM', 'MQ10', 'Comportement M&#xE9;canique Des Mat&#xE9;riaux'),
('GM', 'MQ11', 'Mise En Oeuvre Des Mat&#xE9;riaux'),
('GM', 'MS03', 'Pratique Exp&#xE9;rimentale En Acoustique Et Vibrations'),
('GM', 'PS05', 'Fondements De L\'Acoustique Et Mod&#xE9;lisations'),
('TC', 'BL01', 'Sciences Biologiques Pour L\'Ing&#xE9;nieur'),
('TC', 'MT22', 'Fonctions De Plusieurs Variables R&#xE9;elles Et Applications'),
('TC', 'MT90', 'Fonctions D\'Une Variable Reelle 1'),
('TC', 'PS91', 'Mecanique Physique'),
('TC', 'PS93', 'Optique Geometrique'),
('TC', 'PS94', 'Electricite'),
('TC', 'C2I1', 'Certificat Informatique Et Internet Niveau 1'),
('TC', 'NF01', 'Algorithmique Et Programmation'),
('TC', 'NF92', 'Traitement Automatique De L\'Information'),
('TC', 'PS90', 'Introduction A La Mesure'),
('TC', 'TN01', '&#xE9;l&#xE9;ments De Dessin Technique'),
('TC', 'TN04', 'R&#xE9;alisation'),
('TC', 'CM15', 'Systemes Colloidaux - Applications Agroalimentaires'),
('TC', 'RR01', 'Cin&#xE9;tique Chimique Et R&#xE9;acteurs Homog&#xE8;nes'),
('TC', 'BT02', 'Op&#xE9;rations Agro-Industrielles'),
('TC', 'CM70', 'Travaux Pratiques De Gp (1)'),
('TC', 'TF14', 'Les Op&#xE9;rations De Transfert De Mati&#xE8;re'),
('TC', 'TS01', 'Maitrise Des Risques'),
('TC', 'EL01', 'Ph&#xE9;nom&#xE8;nes Electromagn&#xE9;tiques'),
('TC', 'EL02', '&#xE9;lectricit&#xE9; Industrielle Appliqu&#xE9;e'),
('TC', 'NF15', 'Microprocesseurs, Interfaces Et Logiciels De Bases'),
('TC', 'TN08', 'Dessin De Communication'),
('TC', 'MT10', 'Structures,Calcul Formel Et Algorithmes'),
('TC', 'SR02', 'Syst&#xE8;mes D\'Exploitation : Des Concepts &#xE0; La Programmation'),
('TC', 'SY14', '&#xE9;l&#xE9;ments D\'Automatique'),
('TC', 'LO22', 'Genie Logiciel'),
('TC', 'DD02', 'Introduction A L\'Eco-Conception Et A L\'Analyse De Cycle De Vie'),
('TC', 'UB04', 'Ambiances Et Environnement Lumineux'),
('GM', 'EL01', 'Ph&#xE9;nom&#xE8;nes Electromagn&#xE9;tiques'),
('GM', 'EL02', '&#xE9;lectricit&#xE9; Industrielle Appliqu&#xE9;e'),
('GM', 'NF15', 'Microprocesseurs, Interfaces Et Logiciels De Bases'),
('GM', 'TN08', 'Dessin De Communication'),
('GB', 'BL30', 'Physiologie Des Syst&#xE8;mes Int&#xE9;gr&#xE9;s'),
('GB', 'BL40', 'G&#xE9;nie Cellulaire'),
('GB', 'BM02', 'Organes Artificiels Et Biorheologie'),
('GB', 'BT10', 'Risques Biologiques Et S&#xE9;curit&#xE9; Alimentaire'),
('GB', 'BT21', 'Biotechnologies Moleculaires Et Genie Genetique'),
('GB', 'BT22', 'Les Agroressources'),
('GM', 'SY06', 'Analyse Et Traitement Du Signal'),
('GM', 'SY09', 'Analyse Des Donn&#xE9;es Et Data Mining'),
('GM', 'GPL01', 'Gestion De Production Et Erp (Apprentissage)'),
('GM', 'MAT03', 'Mecanique Des Materiaux (Apprentissage)'),
('GM', 'MC05', 'Machines De Transfert De Fluides'),
('GM', 'MEQ03', 'Dynamique Des Solides (Apprentissage)'),
('GM', 'MQ02', 'M&#xE9;canique Des Solides D&#xE9;formables'),
('GM', 'MQ06', 'Mod&#xE9;lisation Des Structures Par &#xC9;l&#xE9;ments Finis'),
('GM', 'MQ19', 'Dynamique Des Structures'),
('GM', 'TMI01', 'Conception Niveau 2 (Apprentissage)'),
('GM', 'TMI05', 'Fabrication Assistee Par Ordinateur Et Machines A Commande Numerique (Apprentissage)'),
('GM', 'TN12', 'Conception M&#xE9;canique'),
('GM', 'FPP02', 'Fiabilite Et Ingenierie Robuste De Produits (Apprentissage)'),
('GM', 'CT02', 'Maitrise Statistique Des Processus'),
('TC', 'EN21', 'Bases De L\'&#xE9;lectronique Analogique'),
('TC', 'IA02', 'R&#xE9;solution De Probl&#xE8;mes Et Programmation Logique'),
('TC', 'MQ01', '&#xE9;l&#xE9;ments De Resistance Des Mat&#xE9;riaux'),
('TC', 'MQ03', 'M&#xE9;canique Des Vibrations I'),
('TC', 'MQ17', 'Introduction Aux Propri&#xE9;t&#xE9;s M&#xE9;caniques Et &#xE0; L\'Ing&#xE9;nierie Des Mat&#xE9;riaux'),
('TC', 'MQ18', 'Cin&#xE9;matique Et Dynamique Des Syst&#xE8;mes'),
('TC', 'MT12', 'Methodes Mathematiques Pour L\'Analyse Du Signal Et De L\'Image'),
('TC', 'NF04', 'Mod&#xE9;lisation Num&#xE9;rique Des Probl&#xE8;mes De L\'Ing&#xE9;nieur'),
('TC', 'NF16', 'Algorithmique Et Structures De Donn&#xE9;es'),
('TC', 'RO03', 'Recherche Op&#xE9;rationnelle, Optimisation Combinatoire'),
('TC', 'SY02', 'M&#xE9;thodes Statistiques Pour L\'Ing&#xE9;nieur'),
('TC', 'SY04', 'Syst&#xE8;mes Asservis Lin&#xE9;aires : Analyse Et Commande'),
('TC', 'TF01', 'M&#xE9;canique Des Fluides Incompressibles'),
('TC', 'TF06', 'Transfert De Chaleur'),
('TC', 'BA07', 'Modes Op&#xE9;ratoires De La Construction'),
('TC', 'FQ01', '&#xE9;conomie Globale Et Maitrise De La Qualit&#xE9;'),
('TC', 'GE37', 'Gestion De Projet'),
('TC', 'LO01', 'Bases De La Programmation'),
('TC', 'LO21', 'Programmation Et Conception Orientees Objet'),
('TC', 'NF02', 'Du Circuit Int&#xE9;gr&#xE9; Au Microprocesseur'),
('TC', 'NF17', 'Conception De Bases De Donn&#xE9;es'),
('TC', 'NF22', 'Micro-Ordinateurs Et Applications'),
('TC', 'NX17', 'Introduction Aux Bases De Donnees'),
('TC', 'PR', 'R&#xE9;alisation De Projet'),
('TC', 'PS09', 'Acoustique Appliqu&#xE9;e'),
('TC', 'TN02', 'Introduction A La Conception M&#xE9;canique'),
('TC', 'TN20', 'Cao : Mod&#xE9;lisation G&#xE9;om&#xE9;trique'),
('TC', 'TN22', '&#xE9;l&#xE9;ments De Bureau D\'&#xE9;tudes'),
('TC', 'TX', '&#xE9;tude Exp&#xE9;rimentale'),
('TC', 'UR03', 'Cartographie S&#xE9;miologie Graphique Et Cao/Dao'),
('TC', 'UR05', 'Am&#xE9;nagement Et Environnement'),
('GM', 'EN21', 'Bases De L\'&#xE9;lectronique Analogique'),
('GM', 'MQ01', '&#xE9;l&#xE9;ments De Resistance Des Mat&#xE9;riaux'),
('GM', 'MQ03', 'M&#xE9;canique Des Vibrations I'),
('GM', 'MQ17', 'Introduction Aux Propri&#xE9;t&#xE9;s M&#xE9;caniques Et &#xE0; L\'Ing&#xE9;nierie Des Mat&#xE9;riaux'),
('GM', 'MQ18', 'Cin&#xE9;matique Et Dynamique Des Syst&#xE8;mes'),
('GM', 'NF04', 'Mod&#xE9;lisation Num&#xE9;rique Des Probl&#xE8;mes De L\'Ing&#xE9;nieur'),
('GM', 'SY04', 'Syst&#xE8;mes Asservis Lin&#xE9;aires : Analyse Et Commande'),
('GM', 'TF01', 'M&#xE9;canique Des Fluides Incompressibles'),
('GM', 'NF02', 'Du Circuit Int&#xE9;gr&#xE9; Au Microprocesseur'),
('GM', 'NF22', 'Micro-Ordinateurs Et Applications'),
('GM', 'PS09', 'Acoustique Appliqu&#xE9;e'),
('GM', 'TN02', 'Introduction A La Conception M&#xE9;canique'),
('GM', 'TN20', 'Cao : Mod&#xE9;lisation G&#xE9;om&#xE9;trique'),
('GM', 'TN22', '&#xE9;l&#xE9;ments De Bureau D\'&#xE9;tudes'),
('GM', 'DI05', 'Methodologie Et Analyse De La Valeur'),
('GM', 'GE38', 'Management Et Outils D\'Aide &#xE0; La Cr&#xE9;ativit&#xE9; Industrielle Et &#xE0; L\'Innovation'),
('GM', 'GE39', 'Management Et Marketing De L\'Innovation'),
('GM', 'MT12', 'Methodes Mathematiques Pour L\'Analyse Du Signal Et De L\'Image'),
('GM', 'SY02', 'M&#xE9;thodes Statistiques Pour L\'Ing&#xE9;nieur'),
('GM', 'FQ01', '&#xE9;conomie Globale Et Maitrise De La Qualit&#xE9;'),
('GM', 'GE37', 'Gestion De Projet'),
('GM', 'LO01', 'Bases De La Programmation'),
('GM', 'TX', '&#xE9;tude Exp&#xE9;rimentale'),
('GM', 'PR', 'R&#xE9;alisation De Projet'),
('GSU', 'AP', 'Atelier Projet'),
('GSU', 'BA01', 'Equipements Techniques Du Batiment'),
('GSU', 'BA02', 'Gestion Technique Du Patrimoine Immobilier'),
('GSU', 'BA09', 'Introduction Au Calcul Des Structures Du Batiment'),
('GSU', 'UB02', 'Systemes De Transport Urbain'),
('GSU', 'UB06', 'Mises En Sc&#xE8;nes Urbaines'),
('GSU', 'UB08', 'Hydrologie Urbaine'),
('GSU', 'UR01', 'Droit De L\'Urbanisme, De La Construction Et De L\'Environnement'),
('GSU', 'UB04', 'Ambiances Et Environnement Lumineux'),
('GSU', 'MB11', 'R&#xE9;vision D\'Analyse Et D\'Alg&#xE8;bre (Gb, Gi, Gsu)'),
('GSU', 'EV01', 'Proc&#xE9;d&#xE9;s De Traitement Des D&#xE9;chets'),
('GSU', 'BA04', 'Conversion Et Gestion Des Energies Renouvelables'),
('GSU', 'RO03', 'Recherche Op&#xE9;rationnelle, Optimisation Combinatoire'),
('GSU', 'TF06', 'Transfert De Chaleur'),
('GSU', 'BA07', 'Modes Op&#xE9;ratoires De La Construction'),
('GSU', 'NX17', 'Introduction Aux Bases De Donnees'),
('GSU', 'PS09', 'Acoustique Appliqu&#xE9;e'),
('GSU', 'UR03', 'Cartographie S&#xE9;miologie Graphique Et Cao/Dao'),
('GSU', 'UR05', 'Am&#xE9;nagement Et Environnement'),
('GSU', 'MQ01', '&#xE9;l&#xE9;ments De Resistance Des Mat&#xE9;riaux'),
('GSU', 'NF04', 'Mod&#xE9;lisation Num&#xE9;rique Des Probl&#xE8;mes De L\'Ing&#xE9;nieur'),
('GSU', 'GE37', 'Gestion De Projet'),
('GSU', 'LO01', 'Bases De La Programmation'),
('GSU', 'GE38', 'Management Et Outils D\'Aide &#xE0; La Cr&#xE9;ativit&#xE9; Industrielle Et &#xE0; L\'Innovation'),
('GSU', 'GE39', 'Management Et Marketing De L\'Innovation'),
('GSU', 'SY02', 'M&#xE9;thodes Statistiques Pour L\'Ing&#xE9;nieur'),
('GSU', 'FQ01', '&#xE9;conomie Globale Et Maitrise De La Qualit&#xE9;'),
('GSU', 'PR', 'R&#xE9;alisation De Projet'),
('GSU', 'TX', '&#xE9;tude Exp&#xE9;rimentale'),
('GP', 'BT06', 'Analyse Des Produits Biologiques Et Alimentaires'),
('GP', 'CM06', 'Calcul D\'Une Op&#xE9;ration Industrielle'),
('GP', 'CM40', 'Catalyse Heterogene'),
('GP', 'NF24', 'Modelisation Et Simulation Des Procedes'),
('GP', 'SY05', 'Conduite Des Proc&#xE9;d&#xE9;s'),
('GP', 'TA02', '&#xC9;valuation &#xC9;conomique Des Proc&#xE9;d&#xE9;s'),
('GP', 'TF07', 'Calcul Des &#xC9;changeurs Thermiques Industriels'),
('GP', 'TF08', 'Hydrodynamique Des Syst&#xE8;mes Dispers&#xE9;s'),
('GP', 'CM15', 'Systemes Colloidaux - Applications Agroalimentaires'),
('GP', 'RR01', 'Cin&#xE9;tique Chimique Et R&#xE9;acteurs Homog&#xE8;nes'),
('GP', 'BT02', 'Op&#xE9;rations Agro-Industrielles'),
('GP', 'CM70', 'Travaux Pratiques De Gp (1)'),
('GP', 'TF14', 'Les Op&#xE9;rations De Transfert De Mati&#xE8;re'),
('GP', 'TS01', 'Maitrise Des Risques'),
('GP', 'BT10', 'Risques Biologiques Et S&#xE9;curit&#xE9; Alimentaire'),
('GP', 'BT22', 'Les Agroressources'),
('GP', 'EV01', 'Proc&#xE9;d&#xE9;s De Traitement Des D&#xE9;chets'),
('GP', 'BA04', 'Conversion Et Gestion Des Energies Renouvelables'),
('GP', 'TF06', 'Transfert De Chaleur'),
('GP', 'MQ01', '&#xE9;l&#xE9;ments De Resistance Des Mat&#xE9;riaux'),
('GP', 'NF04', 'Mod&#xE9;lisation Num&#xE9;rique Des Probl&#xE8;mes De L\'Ing&#xE9;nieur'),
('GP', 'TF01', 'M&#xE9;canique Des Fluides Incompressibles'),
('GP', 'NF22', 'Micro-Ordinateurs Et Applications'),
('GP', 'GE38', 'Management Et Outils D\'Aide &#xE0; La Cr&#xE9;ativit&#xE9; Industrielle Et &#xE0; L\'Innovation'),
('GP', 'GE39', 'Management Et Marketing De L\'Innovation'),
('GP', 'SY02', 'M&#xE9;thodes Statistiques Pour L\'Ing&#xE9;nieur'),
('GP', 'FQ01', '&#xE9;conomie Globale Et Maitrise De La Qualit&#xE9;'),
('GP', 'TX', '&#xE9;tude Exp&#xE9;rimentale'),
('GP', 'PR', 'R&#xE9;alisation De Projet'),
('GI', 'API06', 'Analyse De Donnees Et Data Mining (Apprentissage)'),
('GI', 'API07', 'Architecture Des Applications Internet, Programmation Web Et Securite (Apprentissage)'),
('GI', 'API08', 'Ihm Et Multim&#xE9;dia (Apprentissage)'),
('GI', 'API09', 'M&#xE9;thodes Et Outils Pour L\'Optimisation Et La Simulation (Apprentissage)'),
('GI', 'API10', 'M&#xE9;thodes De V&#xE9;rification Et Validation De Logiciel Et Programmation Sous Linux (Apprentissage)'),
('GI', 'BI01', 'Modeles Pour La Bioinformatique'),
('GI', 'IA04', 'Syst&#xE8;mes Multiagents'),
('GI', 'LO17', 'Indexation Et Recherche D\'Information'),
('GI', 'LO18', 'Projets Multim&#xE9;dia Pour La Formation'),
('GI', 'MI03', 'Syst&#xE8;mes Temps R&#xE9;el'),
('GI', 'NF11', 'Th&#xE9;orie Des Langages De Programmation'),
('GI', 'NF26', 'Data Warehouse Et Outils D&#xE9;cisionnels'),
('GI', 'NF28', 'Ing&#xE9;nierie Des Syst&#xE8;mes Int&#xE9;ractifs'),
('GI', 'NF33', 'Conception Et Architecture De Syst&#xE8;mes Num&#xE9;riques Informatiques'),
('GI', 'RO04', 'Optimisation Et Recherche Op&#xE9;rationnelle'),
('GI', 'SR03', 'Architecture Des Applications Internet'),
('GI', 'SY15', 'Automatique Avanc&#xE9;e'),
('GI', 'SY26', 'T&#xE9;l&#xE9;communications'),
('GI', 'MT10', 'Structures,Calcul Formel Et Algorithmes'),
('GI', 'SR02', 'Syst&#xE8;mes D\'Exploitation : Des Concepts &#xE0; La Programmation'),
('GI', 'SY14', '&#xE9;l&#xE9;ments D\'Automatique'),
('GI', 'LO22', 'Genie Logiciel'),
('GI', 'MB11', 'R&#xE9;vision D\'Analyse Et D\'Alg&#xE8;bre (Gb, Gi, Gsu)'),
('GI', 'MP02', 'Introduction Aux M&#xE9;thodes De La Gpao'),
('GI', 'SY06', 'Analyse Et Traitement Du Signal'),
('GI', 'SY09', 'Analyse Des Donn&#xE9;es Et Data Mining'),
('GI', 'GE38', 'Management Et Outils D\'Aide &#xE0; La Cr&#xE9;ativit&#xE9; Industrielle Et &#xE0; L\'Innovation'),
('GI', 'GE39', 'Management Et Marketing De L\'Innovation'),
('GI', 'MT12', 'Methodes Mathematiques Pour L\'Analyse Du Signal Et De L\'Image'),
('GI', 'RO03', 'Recherche Op&#xE9;rationnelle, Optimisation Combinatoire'),
('GI', 'SY02', 'M&#xE9;thodes Statistiques Pour L\'Ing&#xE9;nieur'),
('GI', 'FQ01', '&#xE9;conomie Globale Et Maitrise De La Qualit&#xE9;'),
('GI', 'GE37', 'Gestion De Projet'),
('GI', 'TX', '&#xE9;tude Exp&#xE9;rimentale'),
('GI', 'IA02', 'R&#xE9;solution De Probl&#xE8;mes Et Programmation Logique'),
('GI', 'NF16', 'Algorithmique Et Structures De Donn&#xE9;es'),
('GI', 'LO21', 'Programmation Et Conception Orientees Objet'),
('GI', 'NF17', 'Conception De Bases De Donn&#xE9;es'),
('GI', 'PR', 'R&#xE9;alisation De Projet'),
('GSM', 'BM08', 'Mod&#xE9;lisation Des Syst&#xE8;mes Biom&#xE9;caniques'),
('GSM', 'MQ14', 'Optimisation En M&#xE9;canique'),
('GSM', 'MS02', 'Principes Physiques Des Capteurs Et Instrumentation'),
('GSM', 'SY12', 'Mod&#xE9;lisation Et Performance Des Syst&#xE8;mes De Production'),
('GSM', 'TN13', 'Dimensionnement Pour La Conception Des Systemes Mecaniques'),
('GSM', 'TN24', 'Technologies De Fabrication Et Outils M&#xE9;thodes'),
('GSM', 'TN29', 'Outils De Definition Et De Developpement De Systemes'),
('GSM', 'TN30', 'Xao En Milieu Professionnel'),
('GSM', 'DD02', 'Introduction A L\'Eco-Conception Et A L\'Analyse De Cycle De Vie'),
('GSM', 'GPL01', 'Gestion De Production Et Erp (Apprentissage)'),
('GSM', 'MAT03', 'Mecanique Des Materiaux (Apprentissage)'),
('GSM', 'MC05', 'Machines De Transfert De Fluides'),
('GSM', 'MEQ03', 'Dynamique Des Solides (Apprentissage)'),
('GSM', 'MP02', 'Introduction Aux M&#xE9;thodes De La Gpao'),
('GSM', 'MQ02', 'M&#xE9;canique Des Solides D&#xE9;formables'),
('GSM', 'MQ06', 'Mod&#xE9;lisation Des Structures Par &#xC9;l&#xE9;ments Finis'),
('GSM', 'MQ19', 'Dynamique Des Structures'),
('GSM', 'TMI01', 'Conception Niveau 2 (Apprentissage)'),
('GSM', 'TMI05', 'Fabrication Assistee Par Ordinateur Et Machines A Commande Numerique (Apprentissage)'),
('GSM', 'TN12', 'Conception M&#xE9;canique'),
('GSM', 'FPP02', 'Fiabilite Et Ingenierie Robuste De Produits (Apprentissage)'),
('GSM', 'CT02', 'Maitrise Statistique Des Processus'),
('GSM', 'NX17', 'Introduction Aux Bases De Donnees'),
('GSM', 'EN21', 'Bases De L\'&#xE9;lectronique Analogique'),
('GSM', 'MQ01', '&#xE9;l&#xE9;ments De Resistance Des Mat&#xE9;riaux'),
('GSM', 'MQ03', 'M&#xE9;canique Des Vibrations I'),
('GSM', 'MQ17', 'Introduction Aux Propri&#xE9;t&#xE9;s M&#xE9;caniques Et &#xE0; L\'Ing&#xE9;nierie Des Mat&#xE9;riaux'),
('GSM', 'MQ18', 'Cin&#xE9;matique Et Dynamique Des Syst&#xE8;mes'),
('GSM', 'NF04', 'Mod&#xE9;lisation Num&#xE9;rique Des Probl&#xE8;mes De L\'Ing&#xE9;nieur'),
('GSM', 'SY04', 'Syst&#xE8;mes Asservis Lin&#xE9;aires : Analyse Et Commande'),
('GSM', 'TF01', 'M&#xE9;canique Des Fluides Incompressibles'),
('GSM', 'NF02', 'Du Circuit Int&#xE9;gr&#xE9; Au Microprocesseur'),
('GSM', 'NF22', 'Micro-Ordinateurs Et Applications'),
('GSM', 'TN02', 'Introduction A La Conception M&#xE9;canique'),
('GSM', 'TN20', 'Cao : Mod&#xE9;lisation G&#xE9;om&#xE9;trique'),
('GSM', 'TN22', '&#xE9;l&#xE9;ments De Bureau D\'&#xE9;tudes'),
('GSM', 'DI05', 'Methodologie Et Analyse De La Valeur'),
('GSM', 'GE38', 'Management Et Outils D\'Aide &#xE0; La Cr&#xE9;ativit&#xE9; Industrielle Et &#xE0; L\'Innovation'),
('GSM', 'GE39', 'Management Et Marketing De L\'Innovation'),
('GSM', 'MT12', 'Methodes Mathematiques Pour L\'Analyse Du Signal Et De L\'Image'),
('GSM', 'SY02', 'M&#xE9;thodes Statistiques Pour L\'Ing&#xE9;nieur'),
('GSM', 'FQ01', '&#xE9;conomie Globale Et Maitrise De La Qualit&#xE9;'),
('GSM', 'GE37', 'Gestion De Projet'),
('GSM', 'LO01', 'Bases De La Programmation'),
('GSM', 'TX', '&#xE9;tude Exp&#xE9;rimentale'),
('GSM', 'PR', 'R&#xE9;alisation De Projet'),
('HUTECH', 'BL01', 'Sciences Biologiques Pour L\'Ing&#xE9;nieur'),
('HUTECH', 'MT22', 'Fonctions De Plusieurs Variables R&#xE9;elles Et Applications'),
('HUTECH', 'MT90', 'Fonctions D\'Une Variable Reelle 1'),
('HUTECH', 'PS91', 'Mecanique Physique'),
('HUTECH', 'PS93', 'Optique Geometrique'),
('HUTECH', 'PS94', 'Electricite'),
('HUTECH', 'C2I1', 'Certificat Informatique Et Internet Niveau 1'),
('HUTECH', 'NF01', 'Algorithmique Et Programmation'),
('HUTECH', 'NF92', 'Traitement Automatique De L\'Information'),
('HUTECH', 'PS90', 'Introduction A La Mesure'),
('HUTECH', 'TN01', '&#xE9;l&#xE9;ments De Dessin Technique'),
('HUTECH', 'TN04', 'R&#xE9;alisation'),
('HUTECH', 'DI05', 'Methodologie Et Analyse De La Valeur'),
('HUTECH', 'IA02', 'R&#xE9;solution De Probl&#xE8;mes Et Programmation Logique'),
('HUTECH', 'NF16', 'Algorithmique Et Structures De Donn&#xE9;es'),
('HUTECH', 'BA07', 'Modes Op&#xE9;ratoires De La Construction'),
('HUTECH', 'LO01', 'Bases De La Programmation'),
('HUTECH', 'LO21', 'Programmation Et Conception Orientees Objet'),
('HUTECH', 'NF17', 'Conception De Bases De Donn&#xE9;es'),
('HUTECH', 'PR', 'R&#xE9;alisation De Projet'),
('HUTECH', 'UR03', 'Cartographie S&#xE9;miologie Graphique Et Cao/Dao'),
('HUTECH', 'UR05', 'Am&#xE9;nagement Et Environnement');