INSERT INTO `uvbranche` (`branche`, `uv`, `titreuv`) VALUES
('GSU', 'TN10', ''),
('GSU', 'EV01', 'Procédés de traitement des déchets'),
('GSU', 'MT09', 'Analyse numérique'),
('GSU', 'FQ01', 'Économie globale et maitrise de la qualité'),
('GSU', 'SY02', 'Méthodes statistiques pour l'ingénieur'),
('GSU', 'UB10', 'Thermique urbaine'),
('GSU', 'NF04', 'Modélisation numérique des problèmes de l'ingénieur'),
('GSU', 'MB11', 'Révision d'analyse et d'algèbre (gb, gi, gsu)'),
('GSU', 'GE39', 'Management et marketing de l'innovation'),
('GSU', 'GE38', 'Management et outils d'aide à la créativité industrielle et à l'innovation'),
('GSU', 'PS09', 'Acoustique appliquée'),
('GSU', 'TX', 'Étude expérimentale'),
('GSU', 'GE37', 'Gestion de projet'),
('GSU', 'MQ01', 'Éléments de resistance des matériaux'),
('GSU', 'MQ20', 'Introduction a la mécanique des solides et des fluides'),
('GSU', 'RO03', 'Recherche opérationnelle, optimisation combinatoire'),
('GSU', 'SY10', 'Logique floue : concepts et applications'),
('GSU', 'NX17', 'Introduction aux bases de donnees'),
('GSU', 'MT11', ''),
('GSU', 'SY19', 'Decision et apprentissage automatique'),
('GSU', 'TN09', ''),
('GSU', 'UR01', 'Droit de l'urbanisme, de la construction et de l'environnement'),
('GSU', 'AP', 'Atelier projet'),
('GSU', 'UR03', 'Cartographie sémiologie graphique et cao/dao'),
('GSU', 'UR02', 'Théories et pratiques de l'urbanisme contemporain'),
('GSU', 'UR05', 'Aménagement et environnement'),
('GSU', 'UR04', ' outils pour le projet'),
('GSU', 'UR06', 'Géomatique'),
('GSU', 'BA03', 'Matériaux de construction'),
('GSU', 'BA02', 'Gestion technique du patrimoine immobilier'),
('GSU', 'BA01', 'Equipements techniques du batiment'),
('GSU', 'BA07', 'Modes opératoires de la construction'),
('GSU', 'BA06', 'Systèmes constructifs du batiment'),
('GSU', 'BA05', 'Automatismes, régulations et batiments intelligents'),
('GSU', 'BA04', 'Conversion et gestion des energies renouvelables'),
('GSU', 'UB01', 'Composantes des systèmes techniques urbains'),
('GSU', 'UB02', 'Systemes de transport urbain'),
('GSU', 'UB04', 'Ambiances et environnement lumineux'),
('GSU', 'UB07', ''),
('GSU', 'UB06', 'Mises en scènes urbaines'),
('GSU', 'TF06', 'Transfert de chaleur'),
('GSU', 'UB08', 'Hydrologie urbaine'),
('GSU', 'BA09', 'Introduction au calcul des structures du batiment'),
('GSU', 'GE40', 'Management de projets'),
('GSU', 'LO01', 'Bases de la programmation'),
('TSH', 'DPP01', 'Developper son projet professionnel'),
('TSH', 'BC01', 'Redaction bibliographique de fin d'etudes'),
('TSH', 'PIIN', 'Developpement d'un module de formation a distance-multimedia pour l'integration de la propriete industrielle et intellectuelle dans les processus d'inno'),
('TSH', 'EI03', 'Communication interculturelle en entreprises, organisations transnationales'),
('TSH', 'EI04', 'Intelligence économique : stratégie d'entreprise, démarche et outils'),
('TSH', 'EI05', 'Science, technologie et société dans l'union européenne'),
('TSH', 'LG41', 'Portugais niveau i'),
('TSH', 'LG40', 'Portugais initiation'),
('TSH', 'LA01', 'Allemand niveau i'),
('TSH', 'LA00', 'Allemand initiation'),
('TSH', 'LA03', 'Allemand niveau iii'),
('TSH', 'LA02', 'Allemand niveau ii'),
('TSH', 'LA04', 'Pratique de la communication en allemand'),
('TSH', 'SC01', 'Séminaire interdisciplinaire de sciences et technologies cognitives'),
('TSH', 'LC72', 'Anglais master niveau 2'),
('TSH', 'LC73', 'Anglais master niveau 3'),
('TSH', 'LNG14', 'American history and civilization through the cinema (apprentissage)'),
('TSH', 'GE27', 'Gestion financière de l'entreprise'),
('TSH', 'LNG04', 'Anglais niveau iv (apprentissage)'),
('TSH', 'LNG05', 'Anglais professionnel (apprentissage)'),
('TSH', 'LNG01', 'Anglais niveau ii (apprentissage)'),
('TSH', 'LNG02', 'Anglais niveau iii a (apprentissage)'),
('TSH', 'LNG03', 'Anglais niveau iii b (apprentissage)'),
('TSH', 'SC11', 'Théorie des sciences cognitives : computation et énaction'),
('TSH', 'SC12', 'Technologie, cognition, perception'),
('TSH', 'PH09', 'Éthiques : approche pluridisciplinaire'),
('TSH', 'QPO04', 'Qualite et management des organisations'),
('TSH', 'PH01', 'Introduction à la philosophie'),
('TSH', 'PH02', 'L'ingénieur, le philosophe et le scientifique'),
('TSH', 'PH03', 'Penser la techniique aujourd'hui'),
('TSH', 'TN16', 'Étude interculturelle'),
('TSH', 'SL0A', 'Projet individualise (apprentissage)'),
('TSH', 'TN18', ''),
('TSH', 'HT02', 'Histoire, technologie &amp; humanité : les temps de la technique'),
('TSH', 'ASP03', 'Demarches et pratiques en situation professionnelle (apprentissage)'),
('TSH', 'LG61', 'Chinois niveau i'),
('TSH', 'LG60', 'Chinois initiation'),
('TSH', 'LG63', 'Chinois niveau iii'),
('TSH', 'LG62', 'Chinois niveau ii'),
('TSH', 'SIC02', 'Economie des intangibles'),
('TSH', 'SIC03', 'Modélisation et exploration du complexe'),
('TSH', 'GE90', 'Organisation, innovation et international'),
('TSH', 'GE15', 'Initiation a la création et gestion d'entreprises innovantes'),
('TSH', 'GE13', 'Les risques entre technique et societe'),
('TSH', 'GE12', 'Géographie et  économie des territoires'),
('TSH', 'GE10', 'Économie politique'),
('TSH', 'IC03', 'Le numérique : des formats aux chaines de production'),
('TSH', 'LC14', 'Communication scientifique et technique en anglais'),
('TSH', 'PH12', 'L'épreuve du mouvement. de platon a l'ingénieur contemporain'),
('TSH', 'PH11', 'Philosopher aujourd'hui'),
('TSH', 'PH10', 'Analyse phénoménologique des objets audiovisuels'),
('TSH', 'TO02', 'Module de preparation au toefl'),
('TSH', 'SSA03', 'Communication professionnelle (apprentissage)'),
('TSH', 'SSA06', 'Intelligence économique : stratégie d'entreprise, démarche et outils (apprentissage)'),
('TSH', 'SSA04', 'Approches économiques et sociologiques de l'organisation (apprentissage)'),
('TSH', 'VDIN', 'Veille documentaire et technologique sur internet'),
('TSH', 'SO05', 'Sociologie, organisations et dynamiques des collectifs'),
('TSH', 'LB24', 'Le monde hispanique (niveau iv): l'espagne'),
('TSH', 'GE23', 'Transferts de technologies et développements'),
('TSH', 'GE20', 'Économie industrielle'),
('TSH', 'GE21', 'Économie et gestion de l'innovation et du numérique'),
('TSH', 'GE26', 'Management stratégique des ressources humaines'),
('TSH', 'AR03', 'Art et technologies contemporaines'),
('TSH', 'GE25', 'Gestion et organisation de la production'),
('TSH', 'SL00', ''),
('TSH', 'GE28', 'Économie et droit de la propriété intellectuelle (industrielle et artistique) dans une économie reposant sur la connaissance'),
('TSH', 'GE29', 'Gestion et management international de l'entreprise'),
('TSH', 'HE01', 'Épistémologie et histoire des sciences'),
('TSH', 'HE03', 'Logique : histoire et formalisme'),
('TSH', 'HE05', 'Culture et histoire des techniques'),
('TSH', 'SI05', 'Theories de la communication'),
('TSH', 'SI06', 'La documentation technique, principes et méthodes'),
('TSH', 'SI07', 'Medias classiques et medias numeriques'),
('TSH', 'SI01', 'Science et debat public'),
('TSH', 'SI02', 'Communication professionnelle de l'ingénieur'),
('TSH', 'IC05', 'Technologies pour la documentation et l'indexation dans l'hypermédia'),
('TSH', 'IC06', 'Industrie et conception des jeux video'),
('TSH', 'IC07', 'Techniques et technologies du musical et du sonore'),
('TSH', 'IC01', 'Histoire et prospective des industries culturelles'),
('TSH', 'MU03', 'Pratique collective des musiques contemporaines'),
('TSH', 'UE21', 'Management'),
('TSH', 'UE22', 'Gestion de projet de maintenance'),
('TSH', 'UE23', 'Gestion de maintenance'),
('TSH', 'UE24', 'Gestion de production'),
('TSH', 'SP22', 'S'apprendre pour mieux gérer'),
('TSH', 'GE36', 'Marketing'),
('TSH', 'CL01', 'Anglais niveau intermédiaire supérieur'),
('TSH', 'CL02', 'Moi et le monde scientifique '),
('TSH', 'SI90', 'Séminaire de communication des connaissances technologiques'),
('TSH', 'SI14', 'Parole publique en anglais'),
('TSH', 'SI11', 'Expression orale- parole publique'),
('TSH', 'AA01', 'Gestion associative'),
('TSH', 'AV01', 'Initiation à l'analyse et à la réalisation audiovisuelle'),
('TSH', 'LC24', ''),
('TSH', 'SP11', 'Physiologie de l'effort sportif'),
('TSH', 'LB04', 'Interculturalité franco-allemande'),
('TSH', 'SL', 'Suivi linguistique'),
('TSH', 'LG32', 'Japonais niveau ii'),
('TSH', 'AR04', 'Art, ville, architecture'),
('TSH', 'LG30', 'Japonais initiation'),
('TSH', 'LG31', 'Japonais niveau i'),
('TSH', 'UE13', 'Anglais'),
('TSH', 'SA11', 'Pratiques théatrales'),
('TSH', 'UE12', 'Connaissance de l'entreprise'),
('TSH', 'MU02', 'Pratique instrumentale de haut niveau'),
('TSH', 'MG01', 'Management en entreprise : styles de management, construction d'equipe et techniques de travail en groupe'),
('TSH', 'MG02', ''),
('TSH', 'MU01', 'Pratique instrumentale d'ensemble'),
('TSH', 'DI01', 'Initiation au design industriel'),
('TSH', 'DI02', 'Initiation au design graphique'),
('TSH', 'SI22', 'Signes et contenus numeriques'),
('TSH', 'SI20', 'Rhetorique et arts du discours'),
('TSH', 'SP01', 'Un corps pour comprendre et apprendre'),
('TSH', 'SP02', 'Conduire un projet sportif'),
('TSH', 'SI28', 'Écriture interactive et multimédia'),
('TSH', 'LA23', 'Espagnol niveau iii'),
('TSH', 'SC21', 'Linguistique et philosophie du langage'),
('TSH', 'SC22', 'Sociologie cognitive, lien social et techniques'),
('TSH', 'LA20', 'Espagnol initiation'),
('TSH', 'SC24', 'Apprentissage et perception'),
('TSH', 'LA24', 'Le monde hispanique contemporain : l'amérique latine (niveau iv)'),
('TSH', 'LB14', 'Interculturalité appliquée aux pays anglophones'),
('TSH', 'GE22', 'Économie internationale'),
('TSH', 'TO0A', 'Module de preparation au toeic (apprentissage)'),
('TSH', 'AS01', 'Introduction a l'analyse des situations de l'ingenieur'),
('TSH', 'ASP04', 'Connaissances en shs pour l'analyse de situations professionnelles (apprentissage)'),
('TSH', 'ASP06', 'L'ingénieur en situation de management (apprentissage)'),
('TSH', 'SO06', 'Organisation des systèmes de santé'),
('TSH', 'SO04', 'Initiation au droit'),
('TSH', 'LA22', 'Espagnol niveau ii'),
('TSH', 'DD01', 'Séminaire développement durable'),
('TSH', 'IR', ''),
('TSH', 'LA21', 'Espagnol niveau i'),
('TSH', 'TO01', 'Module de preparation au toeic'),
('TSH', 'SC23', ''),
('TSH', 'CP14', 'Montage de projet européens'),
('TSH', 'LG50', 'Italien initiation'),
('TSH', 'LG51', 'Italien niveau i'),
('TSH', 'LG52', 'Italien niveau ii'),
('TSH', 'LG53', 'Italien niveau iii'),
('TSH', 'UE11', 'Communication'),
('TSH', 'LA14', 'Civilisation du monde anglophone'),
('TSH', 'LA15', 'Anglais professionnel - niveau v'),
('TSH', 'LA12', 'Anglais niveau ii'),
('TSH', 'LA13', 'Anglais niveau iii'),
('TSH', 'LA11', 'Anglais niveau i'),
('TSH', 'ICX04', 'Cycle de conferences'),
('TSH', 'LA94', 'Francais langue étrangère niveau iv'),
('TSH', 'SCI09', 'Decouverte d'outils et methodes pour le monde de la recherche scientifique'),
('TSH', 'LA92', 'Francais langue étrangère niveau ii'),
('TSH', 'LA93', 'Francais langue étrangère niveau iii'),
('TSH', 'AS02', 'Accompagnement pour l'analyse des situations de l'ingenieur'),
('TSH', 'LA91', 'Francais langue étrangère niveau i'),
('GP', 'SY05', 'Conduite des procédés'),
('GP', 'TS01', 'Maitrise des risques'),
('GP', 'SY21', ''),
('GP', 'EV01', 'Procédés de traitement des déchets'),
('GP', 'CM70', 'Travaux pratiques de gp (1)'),
('GP', 'CM15', 'Systemes colloidaux - applications agroalimentaires'),
('GP', 'CM14', ''),
('GP', 'TF15', 'Procédés de séparation'),
('GP', 'EV02', 'Conception de procédés propres'),
('GP', 'TN10', ''),
('GP', 'TN15', 'Création de produit, d'activité, d'entreprise'),
('GP', 'FQ03', 'Conception robuste et plans d'experiences'),
('GP', 'FQ01', 'Économie globale et maitrise de la qualité'),
('GP', 'BT06', 'Analyse des produits biologiques et alimentaires'),
('GP', 'RR01', 'Cinétique chimique et réacteurs homogènes'),
('GP', 'RR02', 'Calculs des réacteurs industriels'),
('GP', 'TA02', 'Évaluation économique des procédés'),
('GP', 'BT02', 'Opérations agro-industrielles'),
('GP', 'MT09', 'Analyse numérique'),
('GP', 'TX', 'Étude expérimentale'),
('GP', 'SY10', 'Logique floue : concepts et applications'),
('GP', 'NF04', 'Modélisation numérique des problèmes de l'ingénieur'),
('GP', 'TF14', 'Les opérations de transfert de matière'),
('GP', 'TF16', ''),
('GP', 'TH02', 'Production et transfert de chaleur'),
('GP', 'GE39', 'Management et marketing de l'innovation'),
('GP', 'GE38', 'Management et outils d'aide à la créativité industrielle et à l'innovation'),
('GP', 'TS02', 'Maitriser les risques technologiques majeurs'),
('GP', 'TH04', 'Froid industriel'),
('GP', 'GE37', 'Gestion de projet'),
('GP', 'PR', 'Réalisation de projet'),
('GP', 'SY15', 'Automatique avancée'),
('GP', 'MQ01', 'Éléments de resistance des matériaux'),
('GP', 'CM04', 'Procédés industriels'),
('GP', 'CM05', 'Thermodynamique chimique'),
('GP', 'CM06', 'Calcul d'une opération industrielle'),
('GP', 'CM07', 'Travaux pratiques de génie chimique'),
('GP', 'MT11', ''),
('GP', 'TN09', ''),
('GP', 'PS15', 'Thermodynamique physique'),
('GP', 'CM40', 'Catalyse heterogene'),
('GP', 'BA04', 'Conversion et gestion des energies renouvelables'),
('GP', 'TF08', 'Hydrodynamique des systèmes dispersés'),
('GP', 'TF06', 'Transfert de chaleur'),
('GP', 'TF07', 'Calcul des échangeurs thermiques industriels'),
('GP', 'TF02', 'Dynamique des fluides réels et des gaz'),
('GP', 'TF01', 'Mécanique des fluides incompressibles'),
('GP', 'GE40', 'Management de projets'),
('GP', 'NF22', 'Micro-ordinateurs et applications'),
('GP', 'SY02', 'Méthodes statistiques pour l'ingénieur'),
('GP', 'MA11', 'Révision d'analyse et d'algèbre (gm, gsm, gp)'),
('GP', 'BL16', 'Génie métabolique, cultures cellulaires et bioreacteurs'),
('GB', 'BM07', 'Biocompatibilité'),
('GB', 'BM06', 'Traitement d'images médicales'),
('GB', 'BM05', 'Techniques d'explorations fonctionnelles'),
('GB', 'BM04', 'Acquisition et traitement de données biomédicales'),
('GB', 'TN15', 'Création de produit, d'activité, d'entreprise'),
('GB', 'BM02', 'Organes artificiels et biorheologie'),
('GB', 'BM01', 'Introduction à l'instrumentation biomédicale'),
('GB', 'SY05', 'Conduite des procédés'),
('GB', 'MQ17', 'Introduction aux propriétés mécaniques et à l'ingénierie des matériaux'),
('GB', 'MQ11', 'Mise en oeuvre des matériaux'),
('GB', 'SY06', 'Analyse et traitement du signal'),
('GB', 'BM08', 'Modélisation des systèmes biomécaniques'),
('GB', 'NF22', 'Micro-ordinateurs et applications'),
('GB', 'TN10', ''),
('GB', 'MB11', 'Révision d'analyse et d'algèbre (gb, gi, gsu)'),
('GB', 'FQ03', 'Conception robuste et plans d'experiences'),
('GB', 'FQ01', 'Économie globale et maitrise de la qualité'),
('GB', 'BT06', 'Analyse des produits biologiques et alimentaires'),
('GB', 'BT07', 'Formulation, innovation, nutrition'),
('GB', 'TS01', 'Maitrise des risques'),
('GB', 'FQ04', 'Qualité et exigences réglementaires en génie biologique'),
('GB', 'BT02', 'Opérations agro-industrielles'),
('GB', 'BT03', 'Génie des systèmes tissulaires et immunotechnologie'),
('GB', 'LO01', 'Bases de la programmation'),
('GB', 'TN09', ''),
('GB', 'EV02', 'Conception de procédés propres'),
('GB', 'TF15', 'Procédés de séparation'),
('GB', 'TF14', 'Les opérations de transfert de matière'),
('GB', 'BT09', 'Industries agro-alimentaires - qualites de l'aliment'),
('GB', 'BL20', 'Métabolisme et physiologie cellulaire'),
('GB', 'BL22', 'Microbiologie et biologie moléculaire'),
('GB', 'GE39', 'Management et marketing de l'innovation'),
('GB', 'GE38', 'Management et outils d'aide à la créativité industrielle et à l'innovation'),
('GB', 'TX', 'Étude expérimentale'),
('GB', 'BT21', 'Biotechnologies moleculaires et genie genetique'),
('GB', 'BT22', 'Les agroressources'),
('GB', 'PR', 'Réalisation de projet'),
('GB', 'MQ20', 'Introduction a la mécanique des solides et des fluides'),
('GB', 'MQ07', 'Dégradation et protection des matériaux dans leur environnement'),
('GB', 'MQ04', 'Polymères'),
('GB', 'BL40', 'Génie cellulaire'),
('GB', 'MT11', ''),
('GB', 'SY19', 'Decision et apprentissage automatique'),
('GB', 'SY09', 'Analyse des données et data mining'),
('GB', 'MT12', 'Methodes mathematiques pour l'analyse du signal et de l'image'),
('GB', 'CM15', 'Systemes colloidaux - applications agroalimentaires'),
('GB', 'MQ12', 'Choix des matériaux et des procédés'),
('GB', 'GE37', 'Gestion de projet'),
('GB', 'BT10', 'Risques biologiques et sécurité alimentaire'),
('GB', 'MT09', 'Analyse numérique'),
('GB', 'EN14', 'Fonctions électroniques pour l'ingénieur'),
('GB', 'EN21', 'Bases de l'électronique analogique'),
('GB', 'NF16', 'Algorithmique et structures de données'),
('GB', 'NF15', 'Microprocesseurs, interfaces et logiciels de bases'),
('GB', 'MS01', 'Méthodes d'analyse physico-chimique'),
('GB', 'MS02', 'Principes physiques des capteurs et instrumentation'),
('GB', 'BL30', 'Physiologie des systèmes intégrés'),
('GB', 'SY16', 'Les applications du traitement du signal'),
('GB', 'GE40', 'Management de projets'),
('GB', 'BL10', 'Structures et physicochimie des molécules biologiques'),
('GB', 'SY02', 'Méthodes statistiques pour l'ingénieur'),
('GB', 'NF02', 'Du circuit intégré au microprocesseur'),
('GB', 'BL17', 'Génie des protéines'),
('GB', 'BL16', 'Génie métabolique, cultures cellulaires et bioreacteurs'),
('GM', 'SY04', 'Systèmes asservis linéaires : analyse et commande'),
('GM', 'SY06', 'Analyse et traitement du signal'),
('GM', 'SY02', 'Méthodes statistiques pour l'ingénieur'),
('GM', 'SY03', 'Introduction aux systemes d'entrainements electriques'),
('GM', 'SY08', 'Modélisation des systèmes a évènements discrets'),
('GM', 'SY09', 'Analyse des données et data mining'),
('GM', 'FQ07', 'La qualité des services a l'industrie'),
('GM', 'FQ05', 'Fiabilite industrielle'),
('GM', 'FQ03', 'Conception robuste et plans d'experiences'),
('GM', 'FQ01', 'Économie globale et maitrise de la qualité'),
('GM', 'FPP03', 'Ingénierie robuste et maitrise statistique des procédés (apprentissage)'),
('GM', 'FPP02', 'Fiabilite et ingenierie robuste de produits (apprentissage)'),
('GM', 'FPP01', 'Statistiques generales pour l'ingenieur (apprentissage)'),
('GM', 'LO01', 'Bases de la programmation'),
('GM', 'MAT03', 'Mecanique des materiaux (apprentissage)'),
('GM', 'MAT02', 'Mise en forme des materiaux (apprentissage)'),
('GM', 'MAT01', 'Choix des materiaux et procedes (apprentissage)'),
('GM', 'PS09', 'Acoustique appliquée'),
('GM', 'PS05', 'Fondements de l'acoustique et modélisations'),
('GM', 'SY16', 'Les applications du traitement du signal'),
('GM', 'SY10', 'Logique floue : concepts et applications'),
('GM', 'TN08', 'Dessin de communication'),
('GM', 'TN09', ''),
('GM', 'EN21', 'Bases de l'électronique analogique'),
('GM', 'TF01', 'Mécanique des fluides incompressibles'),
('GM', 'TN10', ''),
('GM', 'TN12', 'Conception mécanique'),
('GM', 'TN15', 'Création de produit, d'activité, d'entreprise'),
('GM', 'PR', 'Réalisation de projet'),
('GM', 'EN14', 'Fonctions électroniques pour l'ingénieur'),
('GM', 'MP02', 'Introduction aux méthodes de la gpao'),
('GM', 'MT11', ''),
('GM', 'MT12', 'Methodes mathematiques pour l'analyse du signal et de l'image'),
('GM', 'MS03', 'Pratique expérimentale en acoustique et vibrations'),
('GM', 'MQ09', 'Mécanique des vibrations ii'),
('GM', 'MA11', 'Révision d'analyse et d'algèbre (gm, gsm, gp)'),
('GM', 'MT09', 'Analyse numérique'),
('GM', 'EG01', 'Ergonomie'),
('GM', 'NF02', 'Du circuit intégré au microprocesseur'),
('GM', 'NF04', 'Modélisation numérique des problèmes de l'ingénieur'),
('GM', 'GE39', 'Management et marketing de l'innovation'),
('GM', 'GE38', 'Management et outils d'aide à la créativité industrielle et à l'innovation'),
('GM', 'GE37', 'Gestion de projet'),
('GM', 'MQ17', 'Introduction aux propriétés mécaniques et à l'ingénierie des matériaux'),
('GM', 'MQ02', 'Mécanique des solides déformables'),
('GM', 'MQ03', 'Mécanique des vibrations i'),
('GM', 'MQ01', 'Éléments de resistance des matériaux'),
('GM', 'MQ06', 'Modélisation des structures par éléments finis'),
('GM', 'MQ07', 'Dégradation et protection des matériaux dans leur environnement'),
('GM', 'TMI09', 'International workshop (apprentissage)'),
('GM', 'TMI08', 'Conception niveau 3 (apprentissage)'),
('GM', 'MEQ02', 'Modelisation numerique niveau 1 (apprentissage)'),
('GM', 'DI05', 'Methodologie et analyse de la valeur'),
('GM', 'MQ08', 'Elaboration et proprietes d'usage des metaux'),
('GM', 'TMI04', 'Technologie de fabrication (apprentissage)'),
('GM', 'TMI03', 'Ergonomie des situations de travail (apprentissage)'),
('GM', 'TMI02', 'Realisation de prototypes (apprentissage)'),
('GM', 'MEQ04', 'Mecanique des fluides (apprentissage)'),
('GM', 'MEQ05', 'Modélisation numérique niveau 2 (apprentissage)'),
('GM', 'MQ13', 'Matériaux composites'),
('GM', 'MQ12', 'Choix des matériaux et des procédés'),
('GM', 'GPL02', 'Recherche operationnelle en productique (apprentissage)'),
('GM', 'GPL03', 'Système de production et usine numérique (apprentissage)'),
('GM', 'GPL01', 'Gestion de production et erp (apprentissage)'),
('GM', 'NF15', 'Microprocesseurs, interfaces et logiciels de bases'),
('GM', 'GE40', 'Management de projets'),
('GM', 'DI08', 'Design industriel et création de produits'),
('GM', 'MQ19', 'Dynamique des structures'),
('GM', 'MQ18', 'Cinématique et dynamique des systèmes'),
('GM', 'DI03', 'Conception formelle des produits'),
('GM', 'MQ11', 'Mise en oeuvre des matériaux'),
('GM', 'MQ10', 'Comportement mécanique des matériaux'),
('GM', 'DI07', 'Design transport'),
('GM', 'DI06', 'Analyse des produits de consommation'),
('GM', 'MQ04', 'Polymères'),
('GM', 'TX', 'Étude expérimentale'),
('GM', 'MQ05', 'Tribologie'),
('GM', 'TMI07', 'Capteurs et instrumentation (apprentissage)'),
('GM', 'MEQ03', 'Dynamique des solides (apprentissage)'),
('GM', 'TMI05', 'Fabrication assistee par ordinateur et machines a commande numerique (apprentissage)'),
('GM', 'CT02', 'Maitrise statistique des processus'),
('GM', 'CT04', 'Controles non destructifs'),
('GM', 'TMI01', 'Conception niveau 2 (apprentissage)'),
('GM', 'TN20', 'Cao :  modélisation géométrique'),
('GM', 'TN21', 'Gestion du cycle de vie du produit et ingenierie collaborative'),
('GM', 'TN22', 'Éléments de bureau d'études'),
('GM', 'TN23', 'Techniques de fabrication'),
('GM', 'EL02', 'Électricité industrielle appliquée'),
('GM', 'EL01', 'Phénomènes electromagnétiques'),
('GM', 'MC01', 'Machines électriques'),
('GM', 'MC02', 'Entrainements électriques à vitesse variable'),
('GM', 'MC05', 'Machines de transfert de fluides'),
('GM', 'MC06', 'Modélisation, dimensionnement, réglages d'axes électromécaniques'),
('GM', 'MC07', 'Électronique de puissance'),
('GM', 'MC08', 'Ingénierie robotique et actionneurs électriques'),
('GM', 'LO18', 'Projets multimédia pour la formation'),
('GM', 'PS14', ''),
('GM', 'MEQ01', 'Modelisation geometrique (apprentissage)'),
('GM', 'PS10', 'Analyse modale en acoustique et vibrations'),
('GM', 'PS12', 'Acoustique architecturale et urbaine'),
('GM', 'PS13', 'Problèmes vibroacoustiques : analyse et modélisation'),
('GSM', 'SY04', 'Systèmes asservis linéaires : analyse et commande'),
('GSM', 'TN10', ''),
('GSM', 'TN13', 'Dimensionnement pour la conception des systemes mecaniques'),
('GSM', 'TN12', 'Conception mécanique'),
('GSM', 'MQ19', 'Dynamique des structures'),
('GSM', 'MQ18', 'Cinématique et dynamique des systèmes'),
('GSM', 'MT09', 'Analyse numérique'),
('GSM', 'SY03', 'Introduction aux systemes d'entrainements electriques'),
('GSM', 'MQ14', 'Optimisation en mécanique'),
('GSM', 'MQ17', 'Introduction aux propriétés mécaniques et à l'ingénierie des matériaux'),
('GSM', 'MQ16', 'Elements finis pour la modelisation de crash et l'analyse d'impacts'),
('GSM', 'SY08', 'Modélisation des systèmes a évènements discrets'),
('GSM', 'BM08', 'Modélisation des systèmes biomécaniques'),
('GSM', 'TN15', 'Création de produit, d'activité, d'entreprise'),
('GSM', 'AP53', 'Production intégrée et logistique'),
('GSM', 'NF22', 'Micro-ordinateurs et applications'),
('GSM', 'TN02', 'Introduction a la conception mécanique'),
('GSM', 'FQ05', 'Fiabilite industrielle'),
('GSM', 'TN30', 'Xao en milieu professionnel'),
('GSM', 'FQ01', 'Économie globale et maitrise de la qualité'),
('GSM', 'TN14', 'Commande hydraulique de puissance'),
('GSM', 'FPP03', 'Ingénierie robuste et maitrise statistique des procédés (apprentissage)'),
('GSM', 'FPP02', 'Fiabilite et ingenierie robuste de produits (apprentissage)'),
('GSM', 'FPP01', 'Statistiques generales pour l'ingenieur (apprentissage)'),
('GSM', 'TN23', 'Techniques de fabrication'),
('GSM', 'SY02', 'Méthodes statistiques pour l'ingénieur'),
('GSM', 'TX', 'Étude expérimentale'),
('GSM', 'GPL02', 'Recherche operationnelle en productique (apprentissage)'),
('GSM', 'DI05', 'Methodologie et analyse de la valeur'),
('GSM', 'SY10', 'Logique floue : concepts et applications'),
('GSM', 'NF04', 'Modélisation numérique des problèmes de l'ingénieur'),
('GSM', 'GPL03', 'Système de production et usine numérique (apprentissage)'),
('GSM', 'MAT03', 'Mecanique des materiaux (apprentissage)'),
('GSM', 'MAT02', 'Mise en forme des materiaux (apprentissage)'),
('GSM', 'MAT01', 'Choix des materiaux et procedes (apprentissage)'),
('GSM', 'GE39', 'Management et marketing de l'innovation'),
('GSM', 'TMI04', 'Technologie de fabrication (apprentissage)'),
('GSM', 'MP02', 'Introduction aux méthodes de la gpao'),
('GSM', 'GE37', 'Gestion de projet'),
('GSM', 'TMI05', 'Fabrication assistee par ordinateur et machines a commande numerique (apprentissage)'),
('GSM', 'CT02', 'Maitrise statistique des processus'),
('GSM', 'GE38', 'Management et outils d'aide à la créativité industrielle et à l'innovation'),
('GSM', 'MQ02', 'Mécanique des solides déformables'),
('GSM', 'MQ03', 'Mécanique des vibrations i'),
('GSM', 'MQ01', 'Éléments de resistance des matériaux'),
('GSM', 'MQ06', 'Modélisation des structures par éléments finis'),
('GSM', 'SY12', 'Modélisation et performance des systèmes de production'),
('GSM', 'TMI09', 'International workshop (apprentissage)'),
('GSM', 'MQ05', 'Tribologie'),
('GSM', 'MEQ02', 'Modelisation numerique niveau 1 (apprentissage)'),
('GSM', 'MEQ03', 'Dynamique des solides (apprentissage)'),
('GSM', 'NX17', 'Introduction aux bases de donnees'),
('GSM', 'MEQ01', 'Modelisation geometrique (apprentissage)'),
('GSM', 'TMI03', 'Ergonomie des situations de travail (apprentissage)'),
('GSM', 'MT11', ''),
('GSM', 'MEQ04', 'Mecanique des fluides (apprentissage)'),
('GSM', 'MEQ05', 'Modélisation numérique niveau 2 (apprentissage)'),
('GSM', 'TN29', 'Outils de definition et de developpement de systemes'),
('GSM', 'RV01', 'Réalité virtuelle'),
('GSM', 'MT12', 'Methodes mathematiques pour l'analyse du signal et de l'image'),
('GSM', 'TMI02', 'Realisation de prototypes (apprentissage)'),
('GSM', 'TN20', 'Cao :  modélisation géométrique'),
('GSM', 'TN21', 'Gestion du cycle de vie du produit et ingenierie collaborative'),
('GSM', 'TN22', 'Éléments de bureau d'études'),
('GSM', 'TN09', ''),
('GSM', 'TN24', 'Technologies de fabrication et outils méthodes'),
('GSM', 'TMI08', 'Conception niveau 3 (apprentissage)'),
('GSM', 'GPL01', 'Gestion de production et erp (apprentissage)'),
('GSM', 'RO06', 'Simulation et techniques d'optimisation'),
('GSM', 'MC05', 'Machines de transfert de fluides'),
('GSM', 'EN21', 'Bases de l'électronique analogique'),
('GSM', 'DD02', 'Introduction a l'eco-conception et a l'analyse de cycle de vie'),
('GSM', 'PS10', 'Analyse modale en acoustique et vibrations'),
('GSM', 'CS02', ''),
('GSM', 'TF01', 'Mécanique des fluides incompressibles'),
('GSM', 'MS02', 'Principes physiques des capteurs et instrumentation'),
('GSM', 'TMI07', 'Capteurs et instrumentation (apprentissage)'),
('GSM', 'TMI01', 'Conception niveau 2 (apprentissage)'),
('GSM', 'PR', 'Réalisation de projet'),
('GSM', 'GE40', 'Management de projets'),
('GSM', 'LO01', 'Bases de la programmation'),
('GSM', 'MA11', 'Révision d'analyse et d'algèbre (gm, gsm, gp)'),
('TC', 'PS94', 'Electricite'),
('TC', 'CM12', 'Chimie physique minérale'),
('TC', 'PS96', 'Ondes et electromagnetisme 2'),
('TC', 'PS90', 'Introduction a la mesure'),
('TC', 'PS91', 'Mecanique physique'),
('TC', 'TN07', ''),
('TC', 'PS93', 'Optique geometrique'),
('TC', 'CM11', 'Chimie générale'),
('TC', 'C2I1', 'Certificat informatique et internet niveau 1'),
('TC', 'SY01', 'Éléments de probabilités'),
('TC', 'PR', 'Réalisation de projet'),
('TC', 'CM13', 'Chimie des substances organiques et biologiques'),
('TC', 'PS22', ''),
('TC', 'TF11', 'Introduction aux phénomènes de transfert'),
('TC', 'NF01', 'Algorithmique et programmation'),
('TC', 'NF02', 'Du circuit intégré au microprocesseur'),
('TC', 'NF03', ''),
('TC', 'PS95', 'Ondes et electromagnetisme 1'),
('TC', 'NP90', 'Nano-projets'),
('TC', 'NP94', 'Preparation scientifique a un sujet "challenge" de tn04'),
('TC', 'BL09', 'Biophysique des systèmes biologiques'),
('TC', 'PS04', 'Thermodynamique'),
('TC', 'BL01', 'Sciences biologiques pour l'ingénieur'),
('TC', 'TN06', 'Transmission des efforts en mécanique'),
('TC', 'CM01', 'Physique de la matière'),
('TC', 'TN04', 'Réalisation'),
('TC', 'TN05', ''),
('TC', 'TN02', 'Introduction a la conception mécanique'),
('TC', 'TN03', 'Fabrication mécanique'),
('TC', 'TN01', 'Éléments de dessin technique'),
('TC', 'MT90', 'Fonctions d'une variable reelle 1'),
('TC', 'MT91', 'Fonctions d'une variable reelle 2'),
('TC', 'NF93', 'Sciences de l'informatique'),
('TC', 'TX', 'Étude expérimentale'),
('TC', 'MT24', ''),
('TC', 'MT23', 'Algèbre linéaire et applications'),
('TC', 'MT22', 'Fonctions de plusieurs variables réelles et applications'),
('TC', 'NF92', 'Traitement automatique de l'information'),
('GI', 'SY23', 'Vision et image'),
('GI', 'SY06', 'Analyse et traitement du signal'),
('GI', 'SY21', ''),
('GI', 'SY26', 'Télécommunications'),
('GI', 'SY27', 'Machines intelligentes'),
('GI', 'SY02', 'Méthodes statistiques pour l'ingénieur'),
('GI', 'TN10', ''),
('GI', 'IA01', 'Intelligence artificielle : représentation'),
('GI', 'NF17', 'Conception de bases de données'),
('GI', 'IA04', 'Systèmes multiagents'),
('GI', 'SY08', 'Modélisation des systèmes a évènements discrets'),
('GI', 'SY09', 'Analyse des données et data mining'),
('GI', 'NF16', 'Algorithmique et structures de données'),
('GI', 'API05', 'Modelisation et simulation des flux (apprentissage)'),
('GI', 'API04', 'Data warehouse et outils decisionnels (apprentissage)'),
('GI', 'API07', 'Architecture des applications internet, programmation web et securite (apprentissage)'),
('GI', 'API06', 'Analyse de donnees et data mining (apprentissage)'),
('GI', 'API01', 'Architecture j2ee et les web services (apprentissage)'),
('GI', 'API03', 'Capteurs intelligents communicants (apprentissage)'),
('GI', 'API02', 'Architecture des réseaux (apprentissage)'),
('GI', 'RV01', 'Réalité virtuelle'),
('GI', 'MB11', 'Révision d'analyse et d'algèbre (gb, gi, gsu)'),
('GI', 'API09', 'Méthodes et outils pour l'optimisation et la simulation (apprentissage)'),
('GI', 'API08', 'Ihm et multimédia (apprentissage)'),
('GI', 'FQ01', 'Économie globale et maitrise de la qualité'),
('GI', 'NF29', 'Ingénierie documentaire et supports d'information'),
('GI', 'MT09', 'Analyse numérique'),
('GI', 'TX', 'Étude expérimentale'),
('GI', 'LO21', 'Programmation et conception orientees objet'),
('GI', 'LO20', ''),
('GI', 'LO23', 'Conduite de projet informatique'),
('GI', 'LO22', 'Genie logiciel'),
('GI', 'GE39', 'Management et marketing de l'innovation'),
('GI', 'GE38', 'Management et outils d'aide à la créativité industrielle et à l'innovation'),
('GI', 'GE37', 'Gestion de projet'),
('GI', 'NF28', 'Ingénierie des systèmes intéractifs'),
('GI', 'SY15', 'Automatique avancée'),
('GI', 'SY14', 'Éléments d'automatique'),
('GI', 'RO03', 'Recherche opérationnelle, optimisation combinatoire'),
('GI', 'RO04', 'Optimisation et recherche opérationnelle'),
('GI', 'IA02', 'Résolution de problèmes et programmation logique'),
('GI', 'MP02', 'Introduction aux méthodes de la gpao'),
('GI', 'LO11', ''),
('GI', 'MT10', 'Structures,calcul formel et algorithmes'),
('GI', 'MT11', ''),
('GI', 'SY19', 'Decision et apprentissage automatique'),
('GI', 'TN09', ''),
('GI', 'NF33', 'Conception et architecture de systèmes numériques informatiques'),
('GI', 'SR04', 'Réseaux informatiques'),
('GI', 'MT12', 'Methodes mathematiques pour l'analyse du signal et de l'image'),
('GI', 'API10', 'Méthodes de vérification et validation de logiciel et programmation sous linux (apprentissage)'),
('GI', 'IA03', 'Techniques de modélisation, capitalisation et gestion des connaissances'),
('GI', 'MI03', 'Systèmes temps réel'),
('GI', 'MI01', 'Structure d'un calculateur'),
('GI', 'SR02', 'Systèmes d'exploitation : des concepts à la programmation'),
('GI', 'RO05', 'Modélisation de phénomènes aléatoires'),
('GI', 'SR06', 'Sécurité systèmes et réseaux'),
('GI', 'SR05', 'Algorithmes et systèmes répartis'),
('GI', 'LO17', 'Indexation et recherche d'information'),
('GI', 'SR03', 'Architecture des applications internet'),
('GI', 'LO12', 'Infographie et images de synthèse'),
('GI', 'SR01', 'Maitrise des systèmes informatiques'),
('GI', 'NF11', 'Théorie des langages de programmation'),
('GI', 'RO06', 'Simulation et techniques d'optimisation'),
('GI', 'LO18', 'Projets multimédia pour la formation'),
('GI', 'LO19', ''),
('GI', 'NF26', 'Data warehouse et outils décisionnels'),
('GI', 'GE40', 'Management de projets');
